
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2016, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 16.10-3

    Combined SIL module
    module taga2
    revision 2017-01-22
    namespace http://iboa.us/ns/taga2
    organization IBOA Corp
    Created: 2017-02-11T00:34:19Z
    CLI parameters:
        format c
        indent 4
        module taga2
        output taga2.c
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_not.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "dlq.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "val_util.h"
#include "xml_util.h"
#include "taga2.h"

/* module static variables */
static ncx_module_t *taga2_mod;
static obj_template_t *taga2_obj;
static obj_template_t *set_blue_state_obj;
static obj_template_t *set_green_state_obj;
static obj_template_t *set_red_state_obj;
static obj_template_t *set_orange_state_obj;
static obj_template_t *set_yellow_state_obj;
static obj_template_t *taga2_change_obj;
static val_value_t *taga2_val;

/* put your static variables here */

/********************************************************************
* FUNCTION y_taga2_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_taga2_init_static_vars (void)
{
    taga2_mod = NULL;
    taga2_obj = NULL;
    set_blue_state_obj = NULL;
    set_green_state_obj = NULL;
    set_red_state_obj = NULL;
    set_orange_state_obj = NULL;
    set_yellow_state_obj = NULL;
    taga2_change_obj = NULL;
    taga2_val = NULL;

    /* init your static variables here */

} /* y_taga2_init_static_vars */


/********************************************************************
* FUNCTION taga2_taga2_taga2_PrimaryState_edit
*
* Edit database object callback
* Path: /taga2/taga2-PrimaryState
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t taga2_taga2_taga2_PrimaryState_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    const xmlChar *newval_val = (newval) ? VAL_ENUM_NAME(newval) : 0;
    const xmlChar *curval_val = (curval) ? VAL_ENUM_NAME(curval) : 0;

    if (LOGDEBUG) {
        log_debug("\nEnter taga2_taga2_taga2_PrimaryState_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* taga2_taga2_taga2_PrimaryState_edit */


/********************************************************************
* FUNCTION taga2_taga2_taga2_SecondaryState_edit
*
* Edit database object callback
* Path: /taga2/taga2-SecondaryState
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t taga2_taga2_taga2_SecondaryState_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    const xmlChar *newval_val = (newval) ? VAL_ENUM_NAME(newval) : 0;
    const xmlChar *curval_val = (curval) ? VAL_ENUM_NAME(curval) : 0;

    if (LOGDEBUG) {
        log_debug("\nEnter taga2_taga2_taga2_SecondaryState_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* taga2_taga2_taga2_SecondaryState_edit */


/********************************************************************
* FUNCTION taga2_taga2_taga2_TertiaryState_edit
*
* Edit database object callback
* Path: /taga2/taga2-TertiaryState
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t taga2_taga2_taga2_TertiaryState_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    const xmlChar *newval_val = (newval) ? VAL_ENUM_NAME(newval) : 0;
    const xmlChar *curval_val = (curval) ? VAL_ENUM_NAME(curval) : 0;

    if (LOGDEBUG) {
        log_debug("\nEnter taga2_taga2_taga2_TertiaryState_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* taga2_taga2_taga2_TertiaryState_edit */


/********************************************************************
* FUNCTION taga2_taga2_stric_state_transitions_edit
*
* Edit database object callback
* Path: /taga2/stric-state-transitions
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t taga2_taga2_stric_state_transitions_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    boolean newval_val = (newval) ? VAL_BOOL(newval) : 0;
    boolean curval_val = (curval) ? VAL_BOOL(curval) : 0;

    if (LOGDEBUG) {
        log_debug("\nEnter taga2_taga2_stric_state_transitions_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* taga2_taga2_stric_state_transitions_edit */


/********************************************************************
* FUNCTION taga2_taga2_edit
*
* Edit database object callback
* Path: /taga2
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t taga2_taga2_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;

    if (LOGDEBUG) {
        log_debug("\nEnter taga2_taga2_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }

        if (res == NO_ERR) {
            res = agt_check_cache(&taga2_val, newval, curval, editop);
        }
        
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* taga2_taga2_edit */


/********************************************************************
* FUNCTION y_taga2_set_blue_state_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_blue_state_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;
    val_value_t *errorval = NULL;

    if (LOGDEBUG) {
        log_debug("\nStart SIL validate rpc <set-blue-state> from module taga2");
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* y_taga2_set_blue_state_validate */


/********************************************************************
* FUNCTION y_taga2_set_blue_state_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_blue_state_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nStart SIL invoke rpc <set-blue-state> from module taga2");
    }

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    
    return res;

} /* y_taga2_set_blue_state_invoke */


/********************************************************************
* FUNCTION y_taga2_set_green_state_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_green_state_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;
    val_value_t *errorval = NULL;

    if (LOGDEBUG) {
        log_debug("\nStart SIL validate rpc <set-green-state> from module taga2");
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* y_taga2_set_green_state_validate */


/********************************************************************
* FUNCTION y_taga2_set_green_state_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_green_state_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nStart SIL invoke rpc <set-green-state> from module taga2");
    }

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    
    return res;

} /* y_taga2_set_green_state_invoke */


/********************************************************************
* FUNCTION y_taga2_set_red_state_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_red_state_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;
    val_value_t *errorval = NULL;

    if (LOGDEBUG) {
        log_debug("\nStart SIL validate rpc <set-red-state> from module taga2");
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* y_taga2_set_red_state_validate */


/********************************************************************
* FUNCTION y_taga2_set_red_state_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_red_state_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nStart SIL invoke rpc <set-red-state> from module taga2");
    }

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    
    return res;

} /* y_taga2_set_red_state_invoke */


/********************************************************************
* FUNCTION y_taga2_set_orange_state_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_orange_state_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;
    val_value_t *errorval = NULL;

    if (LOGDEBUG) {
        log_debug("\nStart SIL validate rpc <set-orange-state> from module taga2");
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* y_taga2_set_orange_state_validate */


/********************************************************************
* FUNCTION y_taga2_set_orange_state_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_orange_state_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nStart SIL invoke rpc <set-orange-state> from module taga2");
    }

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    
    return res;

} /* y_taga2_set_orange_state_invoke */


/********************************************************************
* FUNCTION y_taga2_set_yellow_state_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_yellow_state_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;
    val_value_t *errorval = NULL;

    if (LOGDEBUG) {
        log_debug("\nStart SIL validate rpc <set-yellow-state> from module taga2");
    }

    if (res != NO_ERR) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_OPERATION,
            res,
            methnode,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* y_taga2_set_yellow_state_validate */


/********************************************************************
* FUNCTION y_taga2_set_yellow_state_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t y_taga2_set_yellow_state_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nStart SIL invoke rpc <set-yellow-state> from module taga2");
    }

    /* remove the next line if scb is used */
    (void)scb;

    /* remove the next line if msg is used */
    (void)msg;

    /* remove the next line if methnode is used */
    (void)methnode;

    /* invoke your device instrumentation code here */
    
    return res;

} /* y_taga2_set_yellow_state_invoke */


/********************************************************************
* FUNCTION y_taga2_taga2_change_send
*
* Send a y_taga2_taga2_change notification
* Called by your code when notification event occurs
*
********************************************************************/
void y_taga2_taga2_change_send (
    const xmlChar *taga2_newState)
{
    val_value_t *parmval = NULL;
    status_t res = NO_ERR;

    if (!agt_notifications_enabled()) {
        log_debug2("\nSkipping <taga2-change> notification; disabled");
        return;
    }
    
    if (LOGDEBUG) {
        log_debug("\nGenerating <taga2-change> notification");
    }
    
    agt_not_msg_t *notif = agt_not_new_notification(taga2_change_obj);
    if (notif == NULL) {
        log_error("\nError: malloc failed, cannot send "
        "<taga2-change> notification");
        return;
    }
    
    /* add taga2_newState to payload */
    parmval = agt_make_leaf2(
        taga2_change_obj,
        y_taga2_M_taga2,
        y_taga2_N_taga2_newState,
        taga2_newState,
        &res);
    if (parmval == NULL) {
        log_error(
            "\nError: make leaf failed (%s), cannot send "
            "<taga2-change> notification",
            get_error_string(res));
    } else {
        agt_not_add_to_payload(notif, parmval);
    }
    
    agt_not_queue_notification(notif);
    
} /* y_taga2_taga2_change_send */

/********************************************************************
* FUNCTION y_taga2_init
*
* initialize the taga2 server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_taga2_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    y_taga2_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_taga2_M_taga2)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_taga2_R_taga2)) {
        return ERR_NCX_WRONG_VERSION;
    }


    res = ncxmod_load_module(
        y_taga2_M_taga2,
        y_taga2_R_taga2,
        agt_get_savedevQ(),
        &taga2_mod);
    if (res != NO_ERR) {
        return res;
    }

    taga2_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_taga2);
    if (taga2_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    set_blue_state_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_set_blue_state);
    if (set_blue_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    set_green_state_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_set_green_state);
    if (set_green_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    set_red_state_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_set_red_state);
    if (set_red_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    set_orange_state_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_set_orange_state);
    if (set_orange_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    set_yellow_state_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_set_yellow_state);
    if (set_yellow_state_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    taga2_change_obj = ncx_find_object(
        taga2_mod,
        y_taga2_N_taga2_change);
    if (taga2_change_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_blue_state,
        AGT_RPC_PH_VALIDATE,
        y_taga2_set_blue_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_blue_state,
        AGT_RPC_PH_INVOKE,
        y_taga2_set_blue_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_green_state,
        AGT_RPC_PH_VALIDATE,
        y_taga2_set_green_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_green_state,
        AGT_RPC_PH_INVOKE,
        y_taga2_set_green_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_red_state,
        AGT_RPC_PH_VALIDATE,
        y_taga2_set_red_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_red_state,
        AGT_RPC_PH_INVOKE,
        y_taga2_set_red_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_orange_state,
        AGT_RPC_PH_VALIDATE,
        y_taga2_set_orange_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_orange_state,
        AGT_RPC_PH_INVOKE,
        y_taga2_set_orange_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_yellow_state,
        AGT_RPC_PH_VALIDATE,
        y_taga2_set_yellow_state_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_taga2_M_taga2,
        y_taga2_N_set_yellow_state,
        AGT_RPC_PH_INVOKE,
        y_taga2_set_yellow_state_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2",
        y_taga2_R_taga2,
        taga2_taga2_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-PrimaryState",
        y_taga2_R_taga2,
        taga2_taga2_taga2_PrimaryState_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-SecondaryState",
        y_taga2_R_taga2,
        taga2_taga2_taga2_SecondaryState_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-TertiaryState",
        y_taga2_R_taga2,
        taga2_taga2_taga2_TertiaryState_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:stric-state-transitions",
        y_taga2_R_taga2,
        taga2_taga2_stric_state_transitions_edit);
    if (res != NO_ERR) {
        return res;
    }

    /* put your module initialization code here */
    
    return res;

} /* y_taga2_init */

/********************************************************************
* FUNCTION y_taga2_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_taga2_init2 (void)
{
    status_t res = NO_ERR;

    taga2_val = agt_init_cache(
        y_taga2_M_taga2,
        y_taga2_N_taga2,
        &res);
    if (res != NO_ERR) {
        return res;
    }

    /* put your init2 code here */

    return res;
    
} /* y_taga2_init2 */

/********************************************************************
* FUNCTION y_taga2_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_taga2_cleanup (void)
{

    agt_rpc_unregister_method(
        y_taga2_M_taga2,
        y_taga2_N_set_blue_state);

    agt_rpc_unregister_method(
        y_taga2_M_taga2,
        y_taga2_N_set_green_state);

    agt_rpc_unregister_method(
        y_taga2_M_taga2,
        y_taga2_N_set_red_state);

    agt_rpc_unregister_method(
        y_taga2_M_taga2,
        y_taga2_N_set_orange_state);

    agt_rpc_unregister_method(
        y_taga2_M_taga2,
        y_taga2_N_set_yellow_state);

    agt_cb_unregister_callbacks(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2");

    agt_cb_unregister_callbacks(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-PrimaryState");

    agt_cb_unregister_callbacks(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-SecondaryState");

    agt_cb_unregister_callbacks(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:taga2-TertiaryState");

    agt_cb_unregister_callbacks(
        y_taga2_M_taga2,
        (const xmlChar *)"/taga2:taga2/taga2:stric-state-transitions");

    /* put your cleanup code here */
    
} /* y_taga2_cleanup */

/* END SIL taga2.c */
