
#ifndef _H_taga2
#define _H_taga2
/* 
 * Copyright (c) 2008-2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2016, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 16.10-3

    Combined SIL header
    module taga2
    revision 2017-01-22
    namespace http://iboa.us/ns/taga2
    organization IBOA Corp
    Created: 2017-02-11T00:34:18Z
    CLI parameters:
        format h
        indent 4
        module taga2
        output taga2.h
        unified true

 */

#include <xmlstring.h>

#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "status.h"
#include "val.h"

#ifdef __cplusplus
extern "C" {
#endif

#define y_taga2_M_taga2 (const xmlChar *)"taga2"

#define y_taga2_R_taga2 (const xmlChar *)"2017-01-22"

#define y_taga2_I_taga2_blue (const xmlChar *)"taga2-blue"
#define y_taga2_I_taga2_green (const xmlChar *)"taga2-green"
#define y_taga2_I_taga2_red (const xmlChar *)"taga2-red"
#define y_taga2_I_taga2_orange (const xmlChar *)"taga2-orange"
#define y_taga2_I_taga2_yellow (const xmlChar *)"taga2-yellow"

#define y_taga2_N_set_blue_state (const xmlChar *)"set-blue-state"
#define y_taga2_N_set_green_state (const xmlChar *)"set-green-state"
#define y_taga2_N_set_orange_state (const xmlChar *)"set-orange-state"
#define y_taga2_N_set_red_state (const xmlChar *)"set-red-state"
#define y_taga2_N_set_yellow_state (const xmlChar *)"set-yellow-state"
#define y_taga2_N_stric_state_transitions (const xmlChar *)"stric-state-transitions"
#define y_taga2_N_taga2 (const xmlChar *)"taga2"
#define y_taga2_N_taga2_PrimaryState (const xmlChar *)"taga2-PrimaryState"
#define y_taga2_N_taga2_SecondaryState (const xmlChar *)"taga2-SecondaryState"
#define y_taga2_N_taga2_TertiaryState (const xmlChar *)"taga2-TertiaryState"
#define y_taga2_N_taga2_change (const xmlChar *)"taga2-change"
#define y_taga2_N_taga2_newState (const xmlChar *)"taga2-newState"


/* container /taga2 */
typedef struct y_taga2_T_taga2_ {
    xmlChar *taga2_PrimaryState;
    xmlChar *taga2_SecondaryState;
    xmlChar *taga2_TertiaryState;
    boolean stric_state_transitions;
} y_taga2_T_taga2;

/* container /set-blue-state/input */
typedef struct y_taga2_T_set_blue_state_input_ {
} y_taga2_T_set_blue_state_input;

/* container /set-blue-state/output */
typedef struct y_taga2_T_set_blue_state_output_ {
} y_taga2_T_set_blue_state_output;

/* rpc /set-blue-state */
typedef struct y_taga2_T_set_blue_state_ {
    y_taga2_T_set_blue_state_input input;
    y_taga2_T_set_blue_state_output output;
} y_taga2_T_set_blue_state;

/* container /set-green-state/input */
typedef struct y_taga2_T_set_green_state_input_ {
} y_taga2_T_set_green_state_input;

/* container /set-green-state/output */
typedef struct y_taga2_T_set_green_state_output_ {
} y_taga2_T_set_green_state_output;

/* rpc /set-green-state */
typedef struct y_taga2_T_set_green_state_ {
    y_taga2_T_set_green_state_input input;
    y_taga2_T_set_green_state_output output;
} y_taga2_T_set_green_state;

/* container /set-red-state/input */
typedef struct y_taga2_T_set_red_state_input_ {
} y_taga2_T_set_red_state_input;

/* container /set-red-state/output */
typedef struct y_taga2_T_set_red_state_output_ {
} y_taga2_T_set_red_state_output;

/* rpc /set-red-state */
typedef struct y_taga2_T_set_red_state_ {
    y_taga2_T_set_red_state_input input;
    y_taga2_T_set_red_state_output output;
} y_taga2_T_set_red_state;

/* container /set-orange-state/input */
typedef struct y_taga2_T_set_orange_state_input_ {
} y_taga2_T_set_orange_state_input;

/* container /set-orange-state/output */
typedef struct y_taga2_T_set_orange_state_output_ {
} y_taga2_T_set_orange_state_output;

/* rpc /set-orange-state */
typedef struct y_taga2_T_set_orange_state_ {
    y_taga2_T_set_orange_state_input input;
    y_taga2_T_set_orange_state_output output;
} y_taga2_T_set_orange_state;

/* container /set-yellow-state/input */
typedef struct y_taga2_T_set_yellow_state_input_ {
} y_taga2_T_set_yellow_state_input;

/* container /set-yellow-state/output */
typedef struct y_taga2_T_set_yellow_state_output_ {
} y_taga2_T_set_yellow_state_output;

/* rpc /set-yellow-state */
typedef struct y_taga2_T_set_yellow_state_ {
    y_taga2_T_set_yellow_state_input input;
    y_taga2_T_set_yellow_state_output output;
} y_taga2_T_set_yellow_state;

/* notification /taga2-change */
typedef struct y_taga2_T_taga2_change_ {
    xmlChar *taga2_newState;
} y_taga2_T_taga2_change;


/********************************************************************
* FUNCTION y_taga2_taga2_change_send
*
* Send a y_taga2_taga2_change notification
* Called by your code when notification event occurs
*
********************************************************************/
extern void y_taga2_taga2_change_send (
    const xmlChar *taga2_newState);

/********************************************************************
* FUNCTION y_taga2_init
*
* initialize the taga2 server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
extern status_t y_taga2_init (
    const xmlChar *modname,
    const xmlChar *revision);

/********************************************************************
* FUNCTION y_taga2_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
extern status_t y_taga2_init2 (void);

/********************************************************************
* FUNCTION y_taga2_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
extern void y_taga2_cleanup (void);

#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif